apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flipt.fullname" . }}
  labels:
    {{- include "flipt.labels" . | nindent 4 }}
data:
  default.yml: |
    {{ toYaml .Values.flipt | nindent 4 }}
